name: nnprotscan_2
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - python=3.9
  - numpy
  - matplotlib
  - seaborn
  - pandas
  - biopython
  - tqdm
  - pdb2pqr
  - openmm
  - mdanalysis
  - rdkit
  - pip
